[package]
name = "data-analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3"
calamine = "0.22"
serde = { version = "1.0", features = ["derive"] }
plotters = "0.3"
rand = "0.8"
statrs = "0.16"
anyhow = "1.0"
